<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Kehan Zhou</Authors>
    <Copyright>© 2025–2026 Kehan Zhou</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ViewportControl" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flux2DEditor.Application\Flux2DEditor.Application.csproj" />
    <ProjectReference Include="..\Flux2DEditor.Domain\Flux2DEditor.Domain.csproj" />
  </ItemGroup>

</Project>